<a href="https://colab.research.google.com/github/riya913/WordForThought/blob/main/Week%200/1_Numpy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros

In [2]:
arr = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 ones

In [4]:
arr2 = np.ones(10)
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [6]:
arr3 = np.array([5,5,5,5,5,5,5,5,5,5])
arr3

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [16]:
arr4 = np.arange(10, 51)
print(arr4)
type(arr4[0])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


numpy.int64

#### Create an array of all the even integers from 10 to 50

In [17]:
arr5 = np.arange(10,51,2)
print(arr5)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
arr6 = np.arange(0,9)
arr6.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [20]:
arr7 = np.eye(3)
arr7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [21]:
arr8 = np.random.rand()
print(arr8)

0.407520799435675


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [22]:
arr9 = np.random.randn(25)
print(arr9)

[ 0.23696478  1.20018139  1.25422775  0.33202938  0.55817091  1.67245355
  1.18780371  0.57562232  0.57342155  0.85052388  0.48524894  1.03458329
  0.14545069 -0.43131379 -1.58434385 -0.99619654 -0.8845546  -0.42851298
 -1.74400124 -0.47983892  0.07341239 -0.14800602  0.58908236 -0.84109648
  0.76934696]


#### Create the following matrix:

In [24]:
var_arr = np.arange(0.01,1.01,0.01)
var_arr

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [25]:
var_arr2 = np.linspace(0, 1, 20)
print(var_arr2)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [27]:
var_arr3 = np.arange(1,26).reshape(5,5)
var_arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
var_arr4 = np.arange(12,26).reshape(3,4)

ValueError: cannot reshape array of size 14 into shape (3,4)

20

In [32]:
var_arr5 = np.arange(2,13,5).reshape(3,1)
var_arr5

array([[ 2],
       [ 7],
       [12]])

In [34]:
var_arr6 = np.arange(21,26)
var_arr6

array([21, 22, 23, 24, 25])

In [36]:
var_arr7 = np.arange(16,26).reshape(2,5)
var_arr7

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Great Job!