# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [3]:
import numpy as np

#### Create an array of 10 zeros

In [2]:
arr = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 ones

In [7]:
s_1=np.ones(10)
print(s_1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [10]:
s_5=np.full(10,5.)
print(s_5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Create an array of the integers from 10 to 50

In [14]:
s_r=np.arange(10,51)
print(s_r)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [15]:
s_r=np.arange(10,51,2)
print(s_r)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
s_m=np.arange(0,9).reshape((3,3))
print(s_m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [21]:
s_i=np.eye(3)
print(s_i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [34]:
a=np.random.rand(2)
print(a)

[0.3694333  0.27825966]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [35]:
a_25=np.random.randn(25)
print(a_25)

[-0.53282195 -0.10042891 -0.15749242 -0.93817848  0.46133107 -2.09401292
  0.26256346 -0.75033964 -0.59308432 -1.17467828  1.81214388 -0.2676964
  0.29037513  1.02212615  0.52889201 -0.14054476 -0.67544502  0.50191868
  1.20579821 -0.4024967   0.51992047 -1.05900147 -0.36008491  0.21015055
 -0.06675648]


#### Create the following matrix:

In [39]:
b=np.arange(0.01,1.01,0.01).reshape(10,10)
print(b)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [40]:
c=np.linspace(0,1,20)
print(c)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [42]:
d=np.arange(1,26).reshape(5,5)
print(d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])


In [44]:
e=d[2:,1:]
print(e)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


20

In [45]:
f=d[3,4]
print(f)

20


array([[ 2],
       [ 7],
       [12]])

In [51]:
g=d[:3,1:2]
print(g)

[[ 2]
 [ 7]
 [12]]


array([21, 22, 23, 24, 25])

In [56]:
h=d[4,:]
print(h)

[21 22 23 24 25]


array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])




In [59]:
i=d[3:,:]
print(i)

[[16 17 18 19 20]
 [21 22 23 24 25]]


# Great Job!