<a href="https://colab.research.google.com/github/programming-freak/WordForThought/blob/main/Aditya_Singh_NumpyExercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros

In [2]:
import numpy as np
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
arr = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
import numpy as np
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [27]:
import numpy as np
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [4]:
import numpy as np
arr = np.ones(10)*5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [26]:
import numpy as np
arr = np.ones(10)*5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Create an array of the integers from 10 to 50

In [5]:
import numpy as np
arr = np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [25]:
import numpy as np
arr = np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [7]:
import numpy as np
arr = np.arange(10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [23]:
import numpy as np
arr = np.arange(10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
import numpy as np
arr = np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [22]:
import numpy as np
arr = np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [9]:
import numpy as np
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
import numpy as np
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [10]:
import numpy as np
arr = np.random.rand(1)
print(arr)

[0.85835256]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [11]:
import numpy as np
arr = np.random.randn(25)
print(arr)

[-0.79606488 -0.56631755 -1.26779881  1.2290802  -0.04977743  0.37803689
  0.31928974  1.38324163 -0.05645641  0.08399635  1.34602335  2.19079917
 -0.47040315 -0.74096937 -0.26991615  2.65629202  0.30126056  0.87646879
 -0.18752638 -0.98258848  2.96676057  0.22535548 -0.57558922  0.41167315
 -2.25604647]


In [20]:
import numpy as np
arr = np.random.randn(25)
print(arr)

[-1.8543021   1.27358433  1.76462626  0.7733653   0.38785656  2.15222787
 -0.52767889 -1.73084558 -0.30311524 -1.0478834   2.37370771 -0.51256409
 -1.18456331  0.59522591  1.48976345  1.74391855  0.23035917  0.25030992
 -0.02032134 -0.26418624 -2.24259574 -2.46712427 -0.10943385  1.28221186
 -0.72273097]


#### Create the following matrix:

In [12]:
import numpy as np
arr = np.arange(0.01,1.01,0.01).reshape(10,10)
print(arr)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [13]:
import numpy as np
arr = np.linspace(0,1,20)
print(arr)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [14]:
import numpy as np
arr = np.arange(1,26).reshape(5,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [15]:
import numpy as np
arr = np.arange(12,27).reshape(3,5)
print(arr)

[[12 13 14 15 16]
 [17 18 19 20 21]
 [22 23 24 25 26]]


In [16]:
import numpy as np
arr = np.arange(20,21)
print(arr)

[20]


In [17]:
import numpy as np
arr = np.arange(2,13,5).reshape(3,1)
print(arr)

[[ 2]
 [ 7]
 [12]]


In [18]:
import numpy as np
arr = np.arange(21,26)
print(arr)

[21 22 23 24 25]


In [19]:
import numpy as np
arr = np.arange(16,26).reshape(2,5)
print(arr)

[[16 17 18 19 20]
 [21 22 23 24 25]]


# Great Job!