# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [ ]:
import numpy as np

#### Create an array of 10 zeros

In [ ]:
arr = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
import numpy as np
arr=np.array([1,1,1,1,1,1,1,1,1,1])

#### Create an array of 10 fives

In [4]:
import numpy as np
arr=np.array([5,5,5,5,5,5,5,5,5,5])

#### Create an array of the integers from 10 to 50

In [8]:
import numpy as np
list=[]
for i in range(10 , 51):
    list.append(i)
    arr=np.array(list)

#### Create an array of all the even integers from 10 to 50

In [9]:
import numpy as np
list=[]
for i in range(10,51):
    if i%2==0:
        list.append(i)
        arr=np.array(list)

#### Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
import numpy as np
list=[]
for i in range(0,9):
    list.append(i)
    arr=np.array(list)
newarr=arr.reshape(3,3)

#### Create a 3x3 identity matrix

In [15]:
import numpy as np
arr=np.identity(3)

#### Use NumPy to generate a random number between 0 and 1

In [16]:
import numpy as np
arr=np.random.rand(1)

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [17]:
import numpy as np
arr=np.random.randn(25)

#### Create the following matrix:

In [18]:
import numpy as np
arr=np.arange(0.01,1.01,0.01)
newarr=arr.reshape(10,10)

#### Create an array of 20 linearly spaced points between 0 and 1:

In [20]:
import numpy as np
arr=np.arange(0,1,20)

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [21]:
import numpy as np
arr=np.arange(1,26)

In [22]:
import numpy as np
arr=np.arange(1,26)
newarr=arr.reshape(5,5)

In [23]:
import numpy as np
arr=np.arange(1,26)
newarr=arr.reshape(5,5)
newarr[2:,1:]


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [24]:
import numpy as np
arr=np.arange(1,26)
newarr=arr.reshape(5,5)
newarr[3,4]

20

In [25]:
import numpy as np
arr=np.arange(1,26)
newarr=arr.reshape(5,5)
newarr[4]

array([21, 22, 23, 24, 25])

In [26]:
import numpy as np
arr=np.arange(1,26)
newarr=arr.reshape(5,5)
newarr[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Great Job!