# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros

In [2]:
arr = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 ones

In [3]:
arr1 = np.array([1,1,1,1,1,1,1,1,1,1])

#### Create an array of 10 fives

In [4]:
arr1 = np.array([5,5,5,5,5,5,5,5,5,5])

#### Create an array of the integers from 10 to 50

In [5]:
l=[]
for i in range(10,51):
    l.append(i)
arr = np.array(l)

#### Create an array of all the even integers from 10 to 50

In [7]:
l=[]
for i in range(10,51,2):
  l.append(i)
arr = np.array(l)

#### Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
arr = np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8]])

#### Create a 3x3 identity matrix

In [10]:
arr = np.array([[1,0,0],[0,1,0],[0,0,1]])

#### Use NumPy to generate a random number between 0 and 1

In [12]:
np.random.rand()

0.750743594307056

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [18]:
np.random.normal(0,1,25)

array([-0.15628481,  0.73631154,  0.88582904, -0.6089975 , -0.54089944,
       -0.74333432, -0.52581873,  2.45720026,  0.91496339, -0.97908229,
       -0.1711275 ,  0.30792029, -1.07553745, -0.79967241,  1.12376342,
       -0.21571792,  1.17704692,  1.69380485, -0.71877994,  1.09874503,
        0.83227307, -0.42701003,  0.07434338, -1.22929555, -0.7947611 ])

#### Create the following matrix:

In [16]:
np.random.randn(10,10)

array([[ 2.70570214,  0.52998805, -0.37023449,  0.80213798,  1.15564357,
         0.30291346, -0.34918022,  0.51895412,  0.89054446, -0.00348682],
       [ 1.13549076, -0.55566066, -0.82516407, -0.554988  , -0.22210571,
         0.15575691, -0.02869935,  0.78288224,  1.03655174, -1.20074223],
       [ 1.44068163, -0.19368755, -0.44216209,  1.58495161,  1.19210697,
        -1.67656236, -0.7384915 , -1.75683495,  0.7053952 , -0.1648964 ],
       [-1.1083374 , -0.98595743, -1.33531007, -0.54062101,  1.22510858,
        -0.38711365,  1.88684499,  1.23473976, -0.18606577,  0.3891324 ],
       [ 0.6840015 ,  0.50334039, -1.9222757 , -0.26309345, -1.02272311,
         1.02781904, -0.96043375,  0.76911319, -1.038292  , -0.22623435],
       [-1.24318915,  0.67875865,  1.14505881, -1.58080277, -0.93580084,
         0.2284319 , -0.01811586, -0.71609952, -0.41912735,  1.6713752 ],
       [-0.41802692, -0.02254841, -0.35960647, -0.12996878,  1.3532784 ,
         1.35735227,  0.96305179,  2.56379221

#### Create an array of 20 linearly spaced points between 0 and 1:

In [20]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [30]:
l = []
for i in range(1,26):
  l.append(i)
arr = np.array(l)
arr = np.reshape(arr,(5,5))
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [29]:
l = []
for i in range(1,26):
  l.append(i)
arr = np.array(l)
arr = np.reshape(arr,(5,5))
arr[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [31]:
arr[3,4]

20

In [32]:
arr[3,4]

20

In [34]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [35]:
arr[4]

array([21, 22, 23, 24, 25])

In [36]:
arr[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Great Job!