<a href="https://colab.research.google.com/github/mayankverma341/WordForThought/blob/main/Week%200/01_Numpy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [ ]:
import numpy as np

#### Create an array of 10 zeros

In [38]:
arr = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 ones

In [37]:
arr = np.array([1,1,1,1,1,1,1,1,1,1])

#### Create an array of 10 fives

In [34]:
arr = np.array([5,5,5,5,5,5,5,5,5,5])

#### Create an array of the integers from 10 to 50

In [41]:
arr = np.arange(10,51)

#### Create an array of all the even integers from 10 to 50

In [40]:
arr = np.arange(10,51,2)

#### Create a 3x3 matrix with values ranging from 0 to 8

In [43]:
from numpy import random
arr = random.randint(8,size=(3,3))

#### Create a 3x3 identity matrix

In [44]:
arr = np.array([[1,0,0],[0,1,0],[0,0,1]])

#### Use NumPy to generate a random number between 0 and 1

In [ ]:
from numpy import random
arr = random.rand(1)

array([0.62390023])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
from numpy import random
arr = random.normal(size=(25))

array([-0.11617859, -0.13631661,  0.7150532 , -0.27734985,  0.06538679,
       -1.16994467, -1.45669789,  1.56838663,  1.13525628, -0.69958045,
        0.06961791, -0.07441215,  0.99718638,  0.28416225, -0.14591454,
        0.02658355, -2.05644532,  0.66783981,  2.57474944,  1.3365862 ,
       -0.35696454, -1.57424745,  0.76840978, -0.79557035,  0.91504545])

#### Create the following matrix:

In [47]:
arr= np.linspace(0.01,1,100).reshape(10,10)

#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
arr = np.linespace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
arr = np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
arr = np.arange(1,26).reshape(5,5)
arr1=arr[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
arr = np.arange(1,26).reshape(5,5)
arr1=arr[3,4]

20

In [ ]:
arr = np.arange(1,26).reshape(5,5)
arr1=arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
arr = np.arange(1,26).reshape(5,5)
arr1=arr[4]

array([21, 22, 23, 24, 25])

In [45]:
arr = np.arange(1,26).reshape(5,5)
arr1=arr[3:,0:]

# Great Job!