# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [ ]:
import numpy as np

#### Create an array of 10 zeros

In [ ]:
arr = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 ones

In [ ]:
arr1 = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### Create an array of 10 fives

In [ ]:
arr2 = np.array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

#### Create an array of the integers from 10 to 50

In [ ]:
arr3 = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [ ]:
arr4 = np.array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
arr = np.array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [ ]:
arr = np.array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [ ]:
from numpy import random
x = random.rand()
print(x)

0.31675635002977476


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
import numpy as np
x=np.random.normal(size=25)
print(x)

[-1.10555574 -2.5213121  -1.21263521  1.21519181  0.76234141  0.2972435
 -0.65089801  0.94446116  0.25445413  1.31972095  0.57491574 -0.6980232
 -0.7555092  -0.09462594  0.62018072 -0.86938021  1.19752413 -0.13969663
  0.64063926  0.3735769  -0.79836705  0.93010751  0.74386791 -1.84287257
 -0.33563878]


#### Create the following matrix:

In [ ]:
import numpy as np


matrix = np.linspace(0.01, 1.0, 100).reshape(10, 10)
print(matrix)


[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
import numpy as np
x=np.random.normal(size=25)
print(x)

[-1.38789261  0.59496219 -0.1099075   0.58563569 -0.46733961  0.48886147
 -1.2068728  -0.25684397  0.62986125  1.07873987 -0.46889551 -0.20567538
  1.12612882 -2.0105862  -0.8791843   2.79352236 -0.43991448  0.65097477
 -2.44705734 -0.95419768  0.73574035  0.13369078 -2.3904414   0.95429545
 -1.41668889]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
import numpy as np

matrix = np.arange(1, 26).reshape(5, 5)


print(matrix)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
import numpy as np

full_matrix = np.arange(1, 26).reshape(5, 5)

subarray = full_matrix[2:, 1:]

print(subarray)


[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
import numpy as np

full_matrix = np.arange(1, 26).reshape(5, 5)

subarray = full_matrix[3:4, 4:]

print(subarray)


[[20]]


In [ ]:
import numpy as np

full_matrix = np.arange(1, 26).reshape(5, 5)

subarray = full_matrix[1:2, 0:2]

print(subarray)


[[6 7]]


In [ ]:
import numpy as np

full_matrix = np.arange(1, 26).reshape(5, 5)

subarray = full_matrix[4:, 0:]

print(subarray)


[[21 22 23 24 25]]


In [ ]:
import numpy as np

full_matrix = np.arange(1, 26).reshape(5, 5)

subarray = full_matrix[3:, 0:]

print(subarray)


[[16 17 18 19 20]
 [21 22 23 24 25]]


# Great Job!